spring:
  application:
    name: ms-products
    version: 1.0.0

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100 #Permite que se haga paginacion

  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms #Time out de conexion para evitar que si redis cae nosotros tambien
      username: ${REDIS_USERNAME}

  aop:
    auto: true

server:
  port: 8082

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG # Verás qué endpoint se llamó
    org.springframework.cache: TRACE # <--- IMPORTANTE: Verás qué hace Redis
    org.springframework.data.redis: DEBUG
    com.test.product: DEBUG
